update puppet-strings documentation
I fixed some wrong puppet-strings tags. Sadly I cannot regenerate the
README.md??

```
rake aborted!
NoMethodError: undefined method `any?' for nil:NilClass
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/yard/code_objects/type.rb:153:in `parameters'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/yard/code_objects/type.rb:184:in `to_hash'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:8:in `map!'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:8:in `in_rtypes'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:30:in `toc_info'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/table_of_contents.rb:13:in `block in render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/table_of_contents.rb:12:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/table_of_contents.rb:12:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:19:in `generate'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:38:in `block in render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:38:in `open'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:38:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings.rb:81:in `render_markdown'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings.rb:62:in `generate'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/tasks/generate.rb:43:in `block (2 levels) in <top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/tasks/generate.rb:49:in `block (3 levels) in <top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/Rakefile:24:in `block in <top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/home/bastelfreak/.gem/ruby/2.7.0/bin/bundle:23:in `load'
/home/bastelfreak/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
Tasks: TOP => strings:generate
(See full trace by running task with --trace)
```